server:
  port: 9091

logging:
  level:
    com.paypay: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 1
  sql:
    init:
      mode: always
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql